apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy47
  labels:
    app: autodeploy47
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1719272401976
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy47
  template:
    metadata:
      labels:
        app: autodeploy47
    spec:
      containers:
        - name: autodeploy47
          image: acrworkflow1719272401976.azurecr.io/image-workflow-1719272401976:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
