apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy98
  labels:
    app: autodeploy98
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1720183964344
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy98
  template:
    metadata:
      labels:
        app: autodeploy98
    spec:
      containers:
        - name: autodeploy98
          image: acrworkflow1720183964344.azurecr.io/image-workflow-1720183964344:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
