apiVersion: v1
kind: Service
metadata:
  name: autodeploy47
  namespace: namespace-workflow-1719272401976
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeploy47
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000