apiVersion: v1
kind: Service
metadata:
  name: autodeploy98
  namespace: namespace-workflow-1720183964344
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeploy98
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000